PMS-12 restock and sell
erik-lance/TitafindsXG5 pull request #10
Opened 2022-11-22 09:51 UTC by julianneviz

Screenshot:
![image](https://user-images.githubusercontent.com/83597151/203282455-b8e9c929-bbe4-40b0-8d1c-a61a15b7f3c2.png)
![image](https://user-images.githubusercontent.com/83597151/203282592-03af332a-9805-48a4-9249-a7f692aefd93.png)

Implemented:
- restock item (html, ccs, js)
- sell item (html, ccs, js)
- restock and sell item updates quantity at db
- asynchronous loading to the table displayed
- error message displayed for restock : invalid code
- error messages displayed for sell: invalid code, insufficient stock, no available stock

Need to watch out for:
- unsure on how error messages are displayed

2022-11-22 15:11 UTC, ubergonmx requested changes

2022-11-22 15:11 UTC, aar0npal commented on controllers/itemController.js
> +    checkItem: async function (req, res) {
Whats the difference between this and getItem function?

2022-11-22 15:11 UTC, aar0npal commented on public/js/index.js
> +$(document).ready(function(){
Okay lang si  `$(function () {`

2022-11-22 15:11 UTC, aar0npal commented on public/js/index.js
> +            type: "POST",
Use `GET`

2022-11-22 15:11 UTC, aar0npal commented on public/js/index.js
> +            url: "/checkItem",
Use `/getItem/${code}`. You can use string interpolation.

2022-11-22 15:11 UTC, aar0npal commented on routes/routes.js
> +app.post("/checkItem", upload.any(), itemController.checkItem);
Omit `app.post('/checkItem'...)`.
Use `app.get('/getItem/:code'...)` then use `req.params.code` to get the item code.

2022-11-22 15:11 UTC, aar0npal commented on public/js/index.js
> +            data: data,
`data` is not required for GET http requests.

2022-11-22 15:11 UTC, aar0npal commented on public/js/index.js
> +            url: "/checkItem",
Same here.

2022-11-22 15:11 UTC, aar0npal commented on public/js/index.js
> +                            success: async function (flag) {
Move the error checking under `error` of ajax.

2022-11-22 19:31 UTC, ubergonmx approved these changes

2022-11-23 06:06 UTC, ubergonmx requested changes

2022-11-23 06:06 UTC, ubergonmx commented on controllers/itemController.js
> +            styles: ["index.css", "w2ui-overrides.css", "./general/popup.css"],
Remove `./`

2022-11-23 06:06 UTC, ubergonmx commented on controllers/itemController.js
> +    checkItem: async function (req, res) {
Remove `checkItem`

2022-11-23 06:06 UTC, ubergonmx commented on public/js/index.js
> +                                url: `/getItem/${code}`,
Use `/getItem=:code`

2022-11-23 06:06 UTC, ubergonmx commented on routes/routes.js
> +app.get("/getItem/:code", itemController.getItem);
Change to `/getItem=:code`

2022-11-23 06:18 UTC, ubergonmx approved these changes
Looks good

2022-11-23 13:00 UTC, SeanUmpad commented
**Checked:**
Clicking the ‘Restock’ and ‘Sell’ button shows a pop-up form - Working
‘Sell’ or ‘Restock’ button - Other than the missing validations it is working
‘Cancel’ button - Working

**Test Cases:** https://docs.google.com/spreadsheets/d/1-uWENiTCqkX6zCxiP422kY14om7W3PoVnO5XfAQxOH8

**Errors:** 
Test ID 021: Lacking validation for selling 0 items (might show up sa transactions kasi na sold 0 items)
Test ID 022: Lacking validation for non-numeric text in quantity when selling e.g. "testing"
Test ID 025: Lacking validation for restocking 0 items (might show up sa transactions kasi na restocked 0 items)
Test ID 026: Lacking validation for non-numeric text in quantity when restocking e.g. "testing222e"

Test ID 028-029: Lacking validation for decimals in quantity when restocking/selling (should be whole number)
![image](https://user-images.githubusercontent.com/87850278/203551460-5704dec2-dd41-4ef4-925c-bc4e099bee54.png)
![image](https://user-images.githubusercontent.com/87850278/203551783-401a47a6-caca-48be-8856-f61adb48a5bf.png)

Test ID 030-031 (continuing from test 28-29): If current stock quantity is a decimal the error that should be present for decimals is shown when doing a valid transaction
![image](https://user-images.githubusercontent.com/87850278/203552255-ea0e1cb5-50fa-48a2-9d82-f20ce130a13a.png)

Test ID 032: Pop up form gets messed up when zooming in and out the browser
![image](https://user-images.githubusercontent.com/87850278/203556664-d9e40d96-2fd3-4c23-a235-29f3fce09547.png)

**Notes and Questions:**
- Should the product code be case insensitive?

2022-11-23 13:11 UTC, ubergonmx commented
> Should the product code be case-insensitive?

Yes

2022-11-24 19:45 UTC, SeanUmpad commented
Test ID 032: Pop up form gets messed up when zooming in and out the browser - to be fixed in other pms

2022-11-24 19:50 UTC, SeanUmpad approved these changes

2022-11-25 05:11 UTC, ubergonmx commented
> Test ID 032: Pop up form gets messed up when zooming in and out the browser - to be fixed in other pms
@SeanUmpad 
[T-032 Resolved](https://github.com/erik-lance/TitafindsXG5/pull/10/commits/805b24c71f8f7d9292544985402466a70b83beef)

2022-11-25 05:11 UTC, merged